### ISSUE TITLE
Adapter terminates with error since 2020-08-30 23:08

### ISSUE THREAD

**Issue by ceramgcf** [Pmant/ioBroker.botvac#14]
A few days ago the botvac adapter stopped working.

It gives me the following error messages:
`2020-08-30 23:08:28.123 - error: botvac.0 (4535) uncaught exception: Cannot read property 'isCharging' of undefined
2020-08-30 23:08:28.126 - error: botvac.0 (4535) TypeError: Cannot read property 'isCharging' of undefined
at Robot. (/opt/iobroker/node_modules/node-botvac/lib/robot.js:40:50)
at /opt/iobroker/node_modules/node-botvac/lib/robot.js:320:17
at Request._callback (/opt/iobroker/node_modules/node-botvac/lib/api.js:42:45)
at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request. (/opt/iobroker/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage. (/opt/iobroker/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
2020-08-30 23:08:28.135 - info: botvac.0 (4535) terminating
2020-08-30 23:08:28.138 - info: botvac.0 (4535) Terminated (NO_ERROR): Without reason
2020-08-30 23:09:01.328 - info: botvac.0 (23622) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.botvac, node: v10.20.1, js-controller: 3.0.20
2020-08-30 23:09:03.793 - info: botvac.0 (23622) devices found: 3
2020-08-30 23:09:08.050 - error: botvac.0 (23622) uncaught exception: Cannot read property 'isCharging' of undefined
2020-08-30 23:09:08.052 - error: botvac.0 (23622) TypeError: Cannot read property 'isCharging' of undefined
at Robot. (/opt/iobroker/node_modules/node-botvac/lib/robot.js:40:50)
at /opt/iobroker/node_modules/node-botvac/lib/robot.js:320:17
at Request._callback (/opt/iobroker/node_modules/node-botvac/lib/api.js:42:45)
at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request. (/opt/iobroker/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage. (/opt/iobroker/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
2020-08-30 23:09:08.063 - info: botvac.0 (23622) terminating`

They were preceded by sporadic warnings in this style:

`2020-08-30 18:57:36.403 - warn: botvac.0 (4535) could not update robot Neato`

Unfortunately the adapter is now unusable.

**Comment by masgo** [comment]
I seem to have the same error. It's a fresh installation.


  | 2021-04-08 14:25:27.319 | warn | (30429) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
botvac.0 | 2021-04-08 14:25:27.318 | info | (30429) terminating
botvac.0 | 2021-04-08 14:25:27.297 | error | (30429) Cannot read property 'isCharging' of undefined
botvac.0 | 2021-04-08 14:25:27.297 | error | (30429) TypeError: Cannot read property 'isCharging' of undefined     at Robot.<anonymous> (/opt/iobroker/node_modules/node-botvac/lib/robot.js:40:50)     at /opt/iobroker/node_modules/node-botvac/lib
botvac.0 | 2021-04-08 14:25:27.294 | error | (30429) uncaught exception: Cannot read property 'isCharging' of undefined
botvac.0 | 2021-04-08 14:25:26.261 | info | (30429) devices found: 1
botvac.0 | 2021-04-08 14:25:24.734 | info | (30429) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.botvac, node: v12.22.1, js-controller: 3.2.16
botvac.0 | 2021-04-08 14:24:53.310 | warn | (30414) Terminated (UNCAUGHT_EXCEPTION): Without reason
botvac.0 | 2021-04-08 14:24:53.310 | info | (30414) terminating
botvac.0 | 2021-04-08 14:24:53.294 | error | (30414) Cannot read property 'isCharging' of undefined
botvac.0 | 2021-04-08 14:24:53.293 | error | at IncomingMessage.emit (events.js:326:22)
botvac.0 | 2021-04-08 14:24:53.293 | error | at Object.onceWrapper (events.js:420:28)
botvac.0 | 2021-04-08 14:24:53.293 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12)
botvac.0 | 2021-04-08 14:24:53.293 | error | at Request.emit (events.js:314:20)
botvac.0 | 2021-04-08 14:24:53.293 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10)
botvac.0 | 2021-04-08 14:24:53.293 | error | at Request.emit (events.js:314:20)
botvac.0 | 2021-04-08 14:24:53.293 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
botvac.0 | 2021-04-08 14:24:53.293 | error | at Request._callback (/opt/iobroker/node_modules/node-botvac/lib/api.js:42:45)
botvac.0 | 2021-04-08 14:24:53.293 | error | at /opt/iobroker/node_modules/node-botvac/lib/robot.js:320:17
botvac.0 | 2021-04-08 14:24:53.293 | error | at Robot.<anonymous> (/opt/iobroker/node_modules/node-botvac/lib/robot.js:40:50)
botvac.0 | 2021-04-08 14:24:53.293 | error | (30414) TypeError: Cannot read property 'isCharging' of undefined
botvac.0 | 2021-04-08 14:24:53.290 | error | (30414) uncaught exception: Cannot read property 'isCharging' of undefined
botvac.0 | 2021-04-08 14:24:52.228 | info | (30414) devices found: 1
botvac.0 | 2021-04-08 14:24:50.873 | info | (30414) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.botvac, node: v12.22.1, js-controller: 3.2.16

**Comment by Hini2001** [comment]
I Know this case is closed but i am facing actual the SAME Problem and i cant see here the resolving steps... so can you please tell me what to do, to get the Adapter running as well as it does in the past?

Thank you very much, for your work, your time and now for your help.
